language: php
dist: trusty
sudo: true
php:
  - '7.1'
  - '7.2'
  - nightly
matrix:
  allow_failures:
    - php: nightly
install:
  - composer install
script:
  - sudo apt-get install sshpass
  - sshpass -p 'traivs' ssh -o StrictHostKeyChecking=no travis@localhost exit
  - echo $?
