language: php
dist: trusty
addons:
  ssh_known_hosts: localhost
php:
  - '7.1'
  - '7.2'
  - nightly
matrix:
  allow_failures:
    - php: nightly
install:
  - composer install
script:
  - ssh-keygen -N '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh localhost cat /etc/issue
  - sudo echo How\'s that?
